dist: trusty
sudo: false

language: cpp
compiler: gcc

cache:
  apt: true

script:
 - git clone https://github.com/USCiLab/cereal
 - mkdir build
 - cd build
 - cmake .. -Dcereal_INCLUDE_DIR=$TRAVIS_BUILD_DIR/cereal/include
 - make
 - ./wip_reflect
