dist:
 - trusty

sudo: false

language: cpp
compiler: gcc

cache:
  apt: true

before_install:
 - sudo apt-get install -y libboost-test-dev
 - sudo apt-get install -y libopencv-core-dev

script:
 - apt-get install
 - git clone https://github.com/USCiLab/cereal
 - mkdir build
 - cd build
 - cmake .. -Dcereal_INCLUDE_DIR=$TRAVIS_BUILD_DIR/cereal/include
 - make
 - ./wip_reflect
