dist:
 - trusty

sudo: false

language: cpp
compiler: gcc

cache:
  apt: true

before_install:
 - sudo apt-get install -y libboost-test-dev
 - sudo apt-get install -y libopencv-core-dev

script:
 - git clone https://github.com/USCiLab/cereal
 - mkdir build
 - cd build
 - cmake .. -Dcereal_INCLUDE_DIR=$TRAVIS_BUILD_DIR/cereal/include
 - make
 - cd tests
 - hash/test_ct_string_hash
 - hash/test_ct_object_hash
 - string/test_ct_string_static
 - variadic_typedef/test_ct_variadic_typedef
 - type_trait_detectors/test_ct_type_traits
 