version: 1.0.{build}
image:
- Previous Visual Studio 2017
- Visual Studio 2017
- Visual Studio 2015
- Ubuntu
- Previous Ubuntu

clone_depth: 1
before_build:
- git clone https://github.com/USCiLab/cereal

- cmd: >-
   if not exist "build" mkdir build

   cd build

   cmake .. -DBOOST_ROOT=C:\Libraries\boost_1_67_0 -DBOOST_LIBRARYDIR=C:\Libraries\boost_1_67_0\stage\lib -Dcereal_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%/cereal/include

- sh: >-
    mkdir -p build

    cd build

    cmake .. -Dcereal_INCLUDE_DIR=$APPVEYOR_BUILD_FOLDER/cereal/include

build_script:
- cmd: >-
    msbuild ct.sln

- sh: make

test_script:
- cmd: >-
   cd tests
   
   hash\debug\test_ct_string_hash.exe
   
   hash\debug\test_ct_object_hash.exe
   
   string\debug\test_ct_string_static.exe
   
   variadic_typedef\debug\test_ct_variadic_typedef.exe
 
   type_trait_detectors\debug\test_ct_type_traits.exe


- sh: >-
   cd tests
   
   hash/test_ct_string_hash
   
   hash/test_ct_object_hash
   
   string/test_ct_string_static
   
   variadic_typedef/test_ct_variadic_typedef
 
   type_trait_detectors/test_ct_type_traits
