version: 1.0.{build}
image:
- Previous Visual Studio 2017
- Ubuntu
clone_depth: 1
before_build:
- cmd: >-
   if not exist "build" mkdir build

   cd build

   cmake .. -DBOOST_ROOT=C:\Libraries\boost_1_67_0 -DBOOST_LIBRARYDIR=C:\Libraries\boost_1_67_0\stage\lib
- sh: >-
    mkdir -p build

    cd build
    
    cmake ..
build:
  verbosity: minimal
test_script:
- cmd: wip_reflect