find_package(Python COMPONENTS Interpreter Development NumPy)

if(Python_FOUND)
    message(STATUS "Found python ${Python_VERSION}")
    if(${Python_VERSION} VERSION_GREATER_EQUAL 3.0.0)
        include(${CMAKE_CURRENT_LIST_DIR}/python3.cmake)
    else(${Python_VERSION} VERSION_GREATER_EQUAL 3.0.0)
        include(${CMAKE_CURRENT_LIST_DIR}/python2.cmake)
    endif(${Python_VERSION} VERSION_GREATER_EQUAL 3.0.0)
endif(Python_FOUND)
